# ASP.NET Core (.NET Framework)
# Build and test ASP.NET Core projects targeting the full .NET Framework.
# Add steps that publish symbols, save build artifacts, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/dotnet-core

trigger:
- master

pool:
  vmImage: 'windows-latest'

variables:
  solution: '**/*.sln'
  buildPlatform: 'Any CPU'
  buildConfiguration: 'Release'

steps:

- task: DotNetCoreCLI@2
  displayName: build
  inputs:
    command: 'build'

    
- task: DotNetCoreCLI@2
  displayName: publish
  inputs:
    command: 'publish'
    zipAfterPublish: true
    publishWebProjects: true
    
    
- task: AzureRmWebAppDeployment@4
  displayName: deploy
  inputs:
    ConnectionType: 'AzureRM'
    azureSubscription: 'Azure subscription 1(a4a321cb-975f-4fa4-9a69-02f8d84f45f5)'
    appType: 'webApp'
    WebAppName: 'PlasticFruitStore'
    packageForLinux: '$(System.DefaultWorkingDirectory)/**/*.zip'